export const CarTypes = [
  "SUV",
  "Sedan",
  "Hybrid",
  "Electric",
  "Truck",
  "Van",
  "Wagon",
  "Luxury",
  "Sports Car",
  "Minivan",
  "Pickup",
  "Microcar",
];

export const CarFeatures = [
  "Wireless Charging",
  "Heated Seats",
  "Rearview Camera",
  "Leather Seats",
  "Adaptive Cruise Control",
  "All-Wheel Drive",
  "AC",
  "Bluetooth",
  "Long Range Battery",
  "Towing Package",
  "4-Wheel Drive",
  "Cruise Control",
  "Lane Departure Alert",
  "Apple CarPlay",
  "Blind Spot Monitor",
];

export const AdditionalFeatures = [
  "GPS Navigation System",
  "Child Seat",
  "Insurance",
  "Roof Rack",
  "Portable Tire Inflator",
  "Bicycle Rack",
  "Pet Carrier",
  "Snow Chains",
  "Mobile Phone Charger",
  "Dash Cam",
  "Satellite Radio",
  "Wi-Fi Hotspot",
  "First Aid Kit",
  "Car Cover",
  "Sunshade",
  "Jump Starter Kit",
  "Tool Kit",
  "Fire Extinguisher",
  "Portable Cooler",
  "USB Power Adapter",
];
