export const bangladeshiLocations = [
  { value: "Mirpur, Dhaka", label: "Mirpur, Dhaka" },
  { value: "Dhanmondi, Dhaka", label: "Dhanmondi, Dhaka" },
  { value: "Gulshan, Dhaka", label: "Gulshan, Dhaka" },
  { value: "Banani, Dhaka", label: "Banani, Dhaka" },
  { value: "Uttara, Dhaka", label: "Uttara, Dhaka" },
  { value: "Agrabad, Chittagong", label: "Agrabad, Chittagong" },
  { value: "Chawkbazar, Chittagong", label: "Chawkbazar, Chittagong" },
  { value: "Zindabazar, Sylhet", label: "Zindabazar, Sylhet" },
  { value: "Sonadanga, Khulna", label: "Sonadanga, Khulna" },
  { value: "Kazir Bazar, Rajshahi", label: "Kazir Bazar, Rajshahi" },
  { value: "Barisal Sadar, Barisal", label: "Barisal Sadar, Barisal" },
  { value: "Rangpur City, Rangpur", label: "Rangpur City, Rangpur" },
  {
    value: "Mymensingh Town, Mymensingh",
    label: "Mymensingh Town, Mymensingh",
  },
  { value: "Kuakata, Patuakhali", label: "Kuakata, Patuakhali" },
  { value: "Cox's Bazar, Cox's Bazar", label: "Cox's Bazar, Cox's Bazar" },
  {
    value: "Saint Martin's Island, Cox's Bazar",
    label: "Saint Martin's Island, Cox's Bazar",
  },
  { value: "Rangamati, Rangamati", label: "Rangamati, Rangamati" },
  { value: "Bandarban, Bandarban", label: "Bandarban, Bandarban" },
  { value: "Khagrachari, Khagrachari", label: "Khagrachari, Khagrachari" },
  { value: "Mahasthangarh, Bogra", label: "Mahasthangarh, Bogra" },
  { value: "Paharpur, Naogaon", label: "Paharpur, Naogaon" },
  { value: "Lalbagh Fort, Dhaka", label: "Lalbagh Fort, Dhaka" },
  { value: "The Sundarbans, Khulna", label: "The Sundarbans, Khulna" },
  { value: "Srimangal, Moulvibazar", label: "Srimangal, Moulvibazar" },
  { value: "Sajek Valley, Khagrachari", label: "Sajek Valley, Khagrachari" },
  { value: "Sylhet City, Sylhet", label: "Sylhet City, Sylhet" },
  { value: "Jessore, Jessore", label: "Jessore, Jessore" },
  { value: "Dinajpur, Dinajpur", label: "Dinajpur, Dinajpur" },
  { value: "Bagerhat, Bagerhat", label: "Bagerhat, Bagerhat" },
  { value: "Jhalakathi, Jhalakathi", label: "Jhalakathi, Jhalakathi" },
  { value: "Narayanganj, Narayanganj", label: "Narayanganj, Narayanganj" },
  { value: "Comilla, Comilla", label: "Comilla, Comilla" },
  { value: "Faridpur, Faridpur", label: "Faridpur, Faridpur" },
  { value: "Gaibandha, Gaibandha", label: "Gaibandha, Gaibandha" },
  { value: "Jamalpur, Jamalpur", label: "Jamalpur, Jamalpur" },
  { value: "Kurigram, Kurigram", label: "Kurigram, Kurigram" },
  { value: "Lakshmipur, Lakshmipur", label: "Lakshmipur, Lakshmipur" },
  { value: "Madaripur, Madaripur", label: "Madaripur, Madaripur" },
  { value: "Manikganj, Manikganj", label: "Manikganj, Manikganj" },
  { value: "Munshiganj, Munshiganj", label: "Munshiganj, Munshiganj" },
  { value: "Netrokona, Netrokona", label: "Netrokona, Netrokona" },
  { value: "Noakhali, Noakhali", label: "Noakhali, Noakhali" },
  { value: "Pabna, Pabna", label: "Pabna, Pabna" },
  { value: "Panchagarh, Panchagarh", label: "Panchagarh, Panchagarh" },
  { value: "Patuakhali, Patuakhali", label: "Patuakhali, Patuakhali" },
  { value: "Pirojpur, Pirojpur", label: "Pirojpur, Pirojpur" },
  { value: "Rajbari, Rajbari", label: "Rajbari, Rajbari" },
  { value: "Shariatpur, Shariatpur", label: "Shariatpur, Shariatpur" },
  { value: "Sherpur, Sherpur", label: "Sherpur, Sherpur" },
  { value: "Sunamganj, Sunamganj", label: "Sunamganj, Sunamganj" },
];
